// <auto-generated />
namespace SGCO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Teste : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Teste));
        
        string IMigrationMetadata.Id
        {
            get { return "201805120145428_Teste"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
